### ISSUE TITLE
Compile Fails on macOS due to PyInstaller 

### ISSUE THREAD

**Issue by lbibass** [Ultimaker/cura-build-environment#130]
When attempting to compile Cura, pyinstaller throws this error: 

```Traceback (most recent call last):
  File "/Users/lbibass/git/cura-build-environment/install/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 803, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "/Users/lbibass/git/cura-build-environment/install/installer/Ultimaker-Cura.spec", line 24, in <module>
    a = Analysis(['/Users/lbibass/git/cura-build-environment/install/bin/cura_app.py'],
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 277, in __init__
    self.__postinit__()
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 504, in assemble
    bindepend.Dependencies(self.binaries, redirects=self.binding_redirects, xtrapath=extra_libdirs)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 207, in Dependencies
    for lib, npth in selectImports(pth, xtrapath):
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 459, in selectImports
    dlls = getImports(pth)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 700, in getImports
    return _getImports_macholib(pth)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 600, in _getImports_macholib
    m = MachO(pth)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/macholib/MachO.py", line 118, in __init__
    self.load(fp)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/macholib/MachO.py", line 133, in load
    self.load_header(fh, 0, size)
  File "/Users/lbibass/git/cura-build-environment/install/lib/python3.10/site-packages/macholib/MachO.py", line 167, in load_header
    raise ValueError("Unknown Mach-O header: 0x%08x in %r" % (header, fh))
ValueError: Unknown Mach-O header: 0x213c6172 in <_io.BufferedReader name='/Users/lbibass/git/cura-build-environment/install/lib/python./site-packages/pySavitar.so'>
ninja: build stopped: subcommand failed.
```

It seems it's trying to load non-executable files as executables. I'm not sure how to fix this.

**Comment by jellespijker** [comment]
Which minor version of Python are you using.
There was a bug in pyinstaller which requires at least 3.10.4

**Comment by jellespijker** [comment]
Are you compiling on a M1?

**Comment by lbibass** [comment]
> Are you compiling on a M1?

Yes, I am.

**Comment by jellespijker** [comment]
Then you have to use the Rosetta terminal. We don't support native ARM yet.

**Comment by lbibass** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/27320050/165314884-29c4052b-8a86-4547-a32f-c103802d6be1.png">
So this is bizarre. It just... compiled for me? Not sure what happened, but it worked. Apple Silicon native Cura!

**Comment by jellespijker** [comment]
That is very interesting and unexpected.
Can you share the binaries.

**Comment by lbibass** [comment]
Sure. How would you like me to share them?

**Comment by lbibass** [comment]
I have figured out what I did in order to get it to compile: I had to completely delete the build folder and build from scratch. Attempting to rebuild in a directory that has already been used to compile Cura causes the error. 

What a bizarre glitch.
